# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_dim = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
two_dim = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
three_dim = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [11]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print ("1-dimentional array attributes")
print("shape:", one_dim.shape)
print("number of dimensions:" ,one_dim.ndim)
print("data type:", one_dim.dtype)
print("size:" , one_dim.size)
print("type:", type(one_dim))


1-dimentional array attributes
shape: (3,)
number of dimensions: 1
data type: int32
size: 3
type: <class 'numpy.ndarray'>


In [12]:
# Attributes of 2-dimensional array
print ("2-dimentional array attributes")
print("shape:", two_dim.shape)
print("number of dimensions:" ,two_dim.ndim)
print("data type:", two_dim.dtype)
print("size:" , two_dim.size)
print("type:", type(two_dim))

2-dimentional array attributes
shape: (3, 3)
number of dimensions: 2
data type: int32
size: 9
type: <class 'numpy.ndarray'>


In [13]:
# Attributes of 3-dimensional array

print ("3-dimentional array attributes")
print("shape:", three_dim.shape)
print("number of dimensions:" ,three_dim.ndim)
print("data type:", three_dim.dtype)
print("size:" , three_dim.size)
print("type:", type(three_dim))

3-dimentional array attributes
shape: (2, 2, 2)
number of dimensions: 3
data type: int32
size: 8
type: <class 'numpy.ndarray'>


In [14]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(one_dim)
print(df)

   0
0  1
1  2
2  3


In [15]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
print(zeros)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [17]:
# Create an array within a range of 0 and 100 with step 3
print(np.arange(0, 100, 3))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
print(np.random.rand(7, 2) * 10)

[[9.00724998 0.5053322 ]
 [9.03226826 6.61952088]
 [1.52978662 9.2562098 ]
 [2.43149925 2.21554991]
 [4.91373657 6.52578319]
 [9.81137504 8.99356871]
 [2.93513622 9.55229057]]


In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
print(np.random.rand(3, 5) * 1)

[[0.49065005 0.86062463 0.49573771 0.90392399 0.24907616]
 [0.99914336 0.77359051 0.37663973 0.57746237 0.98149986]
 [0.13598807 0.72435144 0.80193853 0.98575515 0.79251996]]


In [21]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
print(np.random.rand(4, 6) * 10)

[[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864  1.5599452 ]
 [0.58083612 8.66176146 6.01115012 7.08072578 0.20584494 9.69909852]
 [8.32442641 2.12339111 1.81824967 1.8340451  3.04242243 5.24756432]
 [4.31945019 2.9122914  6.11852895 1.39493861 2.92144649 3.66361843]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [22]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.rand(3, 7) * 10

# Find the unique numbers in the array you just created
unique = np.unique(array)
print(unique)

[0.34388521 0.46450413 0.65051593 0.97672114 1.22038235 1.70524124
 1.99673782 2.58779982 3.04613769 4.40152494 4.56069984 4.9517691
 5.14234438 5.92414569 6.07544852 6.84233027 7.85175961 8.08397348
 9.09320402 9.48885537 9.65632033]


In [23]:
# Find the 0'th index of the latest array you created
print(array[0])

[4.56069984 7.85175961 1.99673782 5.14234438 5.92414569 0.46450413
 6.07544852]


In [24]:
# Get the first 2 rows of latest array you created
print(array[:2])

[[4.56069984 7.85175961 1.99673782 5.14234438 5.92414569 0.46450413
  6.07544852]
 [1.70524124 0.65051593 9.48885537 9.65632033 8.08397348 3.04613769
  0.97672114]]


In [25]:
# Get the first 2 values of the first 2 rows of the latest array
print(array[:2, :2])

[[4.56069984 7.85175961]
 [1.70524124 0.65051593]]


In [29]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr1 =  np.random.rand(3, 5) * 10
arr2 = np.ones((3, 5))

print(arr1)
print(arr2)

[[1.19594246 7.13244787 7.60785049 5.61277198 7.7096718 ]
 [4.93795596 5.22732829 4.27541018 0.25419127 1.07891427]
 [0.31429186 6.36410411 3.14355981 5.08570691 9.07566474]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
# Add the two arrays together
sum = arr1 + arr2
print(sum)

[[ 2.19594246  8.13244787  8.60785049  6.61277198  8.7096718 ]
 [ 5.93795596  6.22732829  5.27541018  1.25419127  2.07891427]
 [ 1.31429186  7.36410411  4.14355981  6.08570691 10.07566474]]


In [32]:
# Create another array of ones of shape (5, 3)
arr3 = np.ones((5,3))
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
# Try add the array of ones and the other most recent array together
add = arr2 + arr3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [34]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))

In [38]:
# Subtract the new array of ones from the other most recent array
subtract = sum - ones
print (subtract)

[[1.19594246 7.13244787 7.60785049 5.61277198 7.7096718 ]
 [4.93795596 5.22732829 4.27541018 0.25419127 1.07891427]
 [0.31429186 6.36410411 3.14355981 5.08570691 9.07566474]]


In [39]:
# Multiply the ones array with the latest array
multiply = subtract * ones
print (multiply)

[[1.19594246 7.13244787 7.60785049 5.61277198 7.7096718 ]
 [4.93795596 5.22732829 4.27541018 0.25419127 1.07891427]
 [0.31429186 6.36410411 3.14355981 5.08570691 9.07566474]]


In [40]:
# Take the latest array to the power of 2 using '**'
square_of_multiply = multiply ** 2
print(square_of_multiply)

[[1.43027837e+00 5.08718127e+01 5.78793890e+01 3.15032093e+01
  5.94390393e+01]
 [2.43834091e+01 2.73249611e+01 1.82791322e+01 6.46132004e-02
  1.16405600e+00]
 [9.87793713e-02 4.05018212e+01 9.88196828e+00 2.58644148e+01
  8.23676905e+01]]


In [42]:
# Do the same thing with np.square()
print (np.square(multiply))

[[1.43027837e+00 5.08718127e+01 5.78793890e+01 3.15032093e+01
  5.94390393e+01]
 [2.43834091e+01 2.73249611e+01 1.82791322e+01 6.46132004e-02
  1.16405600e+00]
 [9.87793713e-02 4.05018212e+01 9.88196828e+00 2.58644148e+01
  8.23676905e+01]]


In [43]:
# Find the mean of the latest array using np.mean()
print(np.mean(square_of_multiply))

28.736971615782178


In [44]:
# Find the maximum of the latest array using np.max()
print (np.max(square_of_multiply))

82.36769045946416


In [45]:
# Find the minimum of the latest array using np.min()
print(np.min(square_of_multiply))

0.06461320044323753


In [46]:
# Find the standard deviation of the latest array
std_dev = np.std(square_of_multiply)
print(std_dev)

24.42186749369064


In [47]:
# Find the variance of the latest array
variance = np.var(square_of_multiply)
print(variance)

596.4276118793837


In [49]:
# Reshape the latest array to (3, 5, 1)
reshaped = square_of_multiply.reshape(3, 5, 1)
print (reshaped)

[[[1.43027837e+00]
  [5.08718127e+01]
  [5.78793890e+01]
  [3.15032093e+01]
  [5.94390393e+01]]

 [[2.43834091e+01]
  [2.73249611e+01]
  [1.82791322e+01]
  [6.46132004e-02]
  [1.16405600e+00]]

 [[9.87793713e-02]
  [4.05018212e+01]
  [9.88196828e+00]
  [2.58644148e+01]
  [8.23676905e+01]]]


In [50]:
# Transpose the latest array
# Transpose the array
# Transpose the array
transposed = reshaped.T

print(transposed)

[[[1.43027837e+00 2.43834091e+01 9.87793713e-02]
  [5.08718127e+01 2.73249611e+01 4.05018212e+01]
  [5.78793890e+01 1.82791322e+01 9.88196828e+00]
  [3.15032093e+01 6.46132004e-02 2.58644148e+01]
  [5.94390393e+01 1.16405600e+00 8.23676905e+01]]]


What does the transpose do?

In [51]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.rand(3, 3)
arr2 = np.random.rand(3, 2)

print(arr1)
print(arr2)

[[0.24929223 0.41038292 0.75555114]
 [0.22879817 0.07697991 0.28975145]
 [0.16122129 0.92969765 0.80812038]]
[[0.63340376 0.87146059]
 [0.80367208 0.18657006]
 [0.892559   0.53934224]]


In [52]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(arr1, arr2)
print(dot_product)

[[1.1620899  0.70131416]
 [0.46540849 0.37002593]
 [1.57058533 0.7498052 ]]


In [53]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand1 = np.random.randint(0, 11, size=(4, 3))
rand2 = np.random.randint(0, 11, size=(4, 3))

print(rand1)
print(rand2)

[[ 9  6  8]
 [ 6  0  0]
 [ 8 10  8]
 [ 3  8  2]]
[[ 6  5  7]
 [10  8  4]
 [ 0  2  9]
 [ 7 10  5]]


In [54]:
# Perform a dot product on the two newest arrays you created
dot_product2 = np.dot(rand1, rand2)
print(dot_product2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [56]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
rand1_transposed = rand1.T
dot = np.dot(rand1_transposed, rand2)

print(dot)

[[135 139 174]
 [ 92 130 172]
 [ 62  76 138]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [57]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
first_rand = np.random.randint(0,11, size=(4, 4))
second_rand = np.random.randint(0,11, size=(4, 4))

print(first_rand)
print(second_rand)

[[ 7  8  3  0]
 [ 0  9  3  6]
 [ 1  2  0  4]
 [ 0  7  0 10]]
[[0 1 1 5]
 [6 4 0 0]
 [2 1 4 9]
 [5 6 3 6]]


In [58]:
# Compare the two arrays with '>'
print(first_rand > second_rand)

[[ True  True  True False]
 [False  True  True  True]
 [False  True False False]
 [False  True False  True]]


What happens when you compare the arrays with `>`?

In [59]:
# Compare the two arrays with '>='
print(first_rand >= second_rand)

[[ True  True  True False]
 [False  True  True  True]
 [False  True False False]
 [False  True False  True]]


In [62]:
# Find which elements of the first array are greater than 7
print(first_rand > 7)

[[False  True False False]
 [False  True False False]
 [False False False False]
 [False False False  True]]


In [63]:
# Which parts of each array are equal? (try using '==')
print(first_rand == second_rand)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [64]:
# Sort one of the arrays you just created in ascending order
sorted_arr = np.sort(first_rand)
print(sorted_arr)

[[ 0  3  7  8]
 [ 0  3  6  9]
 [ 0  1  2  4]
 [ 0  0  7 10]]


In [67]:
# Sort the indexes of one of the arrays you just created
sorted_indeces = np.argsort(sorted_arr)
print(sorted_indeces)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [70]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(first_rand)
max_row, max_col = np.unravel_index(max_index, first_rand.shape)

print("Index with maximum value:", max_row, max_col)


Index with maximum value: 3 3


In [71]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(first_rand)
min_row, min_col = np.unravel_index(min_index, first_rand.shape)

print("Index with minimum value:", min_row, min_col)

Index with minimum value: 0 3


In [75]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indexes = np.argmax(first_rand, axis=1)

print("Indexes with maximum values down the 1st axis (axis=1):", max_indexes)

Indexes with maximum values down the 1st axis (axis=1): [1 1 3 3]


In [78]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indexes = np.argmin(first_rand, axis=0)

print("Indexes with minimum values down the 0th axis (axis=0):", min_indexes)

Indexes with minimum values down the 0th axis (axis=0): [1 2 2 0]


In [79]:
# Create an array of normally distributed random numbers
mean = 0 
std_dev = 1  
size = (4, 3)  

normal_dist_arr = np.random.normal(mean, std_dev, size)

print(normal_dist_arr)

[[ 0.00914435 -0.3655393   0.64908673]
 [-1.22287354  0.53633603 -0.91469093]
 [ 0.62054822 -0.16093738 -0.3882644 ]
 [-0.88551237 -0.35674503  0.5561218 ]]


In [80]:
# Create an array with 10 evenly spaced numbers between 1 and 100
print(np.linspace(1, 100, 10))


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.